import { FORM_URLS } from "../config/site.config";

export type FormType = "exhibitor" | "visitor" | "contact";

export type RegistrationPayload = {
  type: FormType;
  id?: string;
  personal: Record<string, string>;
  company?: Record<string, string>;
  interest?: string;
  message?: string;
  passImage?: string;
  passPdf?: string;
  /** Toggle: whether to attach the pass PNG as a downloadable file to the email (default: true) */
  attachImage?: boolean;
  /** Toggle: whether to attach the pass PDF as a downloadable file to the email (default: true) */
  attachPdf?: boolean;
  /** URLs of public files (e.g. brochure PDF) to fetch and attach to the email */
  attachments?: { url: string; name: string }[];
};

export type SubmissionResult = {
  ok: boolean;
  id?: string;        // Real Unique ID returned by the backend (source of truth)
  offline?: boolean;  // True when no backend URL is configured
  status?: number;
  error?: string;
};

/**
 * Submit a form registration to its dedicated Google Apps Script Web App.
 * Uses standard CORS mode so we can READ the backend response, including
 * the real Unique ID generated by the Apps Script (based on sheet row count).
 *
 * Google Apps Script Web Apps support CORS when:
 *  - Deployed with "Anyone" access
 *  - Content-Type is "text/plain" (avoids CORS preflight)
 */
export async function submitRegistration(
  payload: RegistrationPayload
): Promise<SubmissionResult> {
  const formUrls: Record<string, string> = FORM_URLS;
  const url = formUrls[payload.type] || "";

  if (!url) {
    console.info("[Registration Submission Payload - Backend disabled]", payload);
    return { ok: true, offline: true };
  }

  try {
    const res = await fetch(url, {
      method: "POST",
      redirect: "follow",
      headers: { "Content-Type": "text/plain;charset=utf-8" },
      body: JSON.stringify(payload),
    });

    // Try to parse JSON response containing { ok, id }
    let data: { ok?: boolean; id?: string; error?: string } = {};
    try {
      data = await res.json();
    } catch {
      // Response was not JSON (edge case); still consider it successful
    }

    return {
      ok: data.ok !== false,
      id: data.id,
      status: res.status,
      error: data.error,
    };
  } catch (err) {
    console.error("[Submission Failed]", err);
    return { ok: false, error: String(err) };
  }
}
